### ISSUE TITLE
[P_Siren] - when entering "stunned" state, attacks are disabled for an extended period of time

### ISSUE THREAD

**Issue by nr42111** [KFPilot/KFTurbo#12]
Bug: sirens cannot attack or scream after getting hit with a high enough damage hit to trigger a "stun" while in walking mode / scream chargeup state or screaming state

Replication: 
Wait for the Siren to enter "screaming windup" state (pathing replaced by walking)
Deal a high amount of damage without killing it  (crossbow bodyshot is very consistent)
After the first scream, observe all of the siren's attacks being disabled for ~30 seconds.

**Comment by KFPilot** [comment]
Fixed by b454525. No longer occurs in dedicated server game.
