### ISSUE TITLE
Orca bomb propeller - damage bonus for bouncing

### ISSUE THREAD

**Issue by nr42111** [KFPilot/KFTurbo#23]
Create a sane way of adding bonus damage for the orca bomb propeller

- players should be incentivized to land "trick shots" with high damage multipliers for a "stylish" bounce
- need to minimize abuse of "rolling" a bomb across the floor for big damage numbers with 0 effort
- orca bomb needs to be a straight upgrade to m79 in closed-quarters holding spots
- 1 bounce should break even with a full upper torso hit
- 2 bounces should have a big payoff
- 3 bounces should instakill all small zeds(up to gore) in the explosion radius

Things to consider:
- Minimum time between bounces
- Minimum projectile speed to award a multiplier
- Cap the multiplier stack (bounce counter)
- Minimum distance between bounces (cache last bounce location, and use vector length)

**Comment by KFPilot** [comment]
Implemented in 95725e8.
