### ISSUE TITLE
Weird crash when opening specific maps in solo with ServerVeterancyHandler mutator enabled

### ISSUE THREAD

**Issue by nr42111** [KFPilot/KFTurbo#30]
The map does not load in, it crashes during loading.
Reproduction rate: 100%
Reproduction steps: 
- solo mode
- select killing floor gamemode
- select a map from the list below
- add serverveterancyhandler mutator
- observe crash

![genprotfa](https://github.com/user-attachments/assets/46a71bad-80de-47df-ab2c-ff9dd977e9df)
[KillingFloor.log](https://github.com/user-attachments/files/16202137/KillingFloor.log)

Affected maps:
KF-Bedlam
KF-Biohazard
KF-Clandestine
KF-EvilSantasLair
KF-FrightYard
KF-Hellride
KF-HospitalHorrors
KF-MountainPass
KF-Stronghold
KF-ThrillsChills

**Comment by KFPilot** [comment]
Seems like a weird Server Perks issue. Crash data has been very helpful. Closing as won't fix (unless more useful information comes up).
