### ISSUE TITLE
Single reload weapons show 1 ammo remaining but in fact have nothing left

### ISSUE THREAD

**Issue by nr42111** [KFPilot/KFTurbo#31]
M79, Orca Bomb propeller, probably LAW and M99.

Ammo display says 1 after shooting the last shot.

**Comment by nr42111** [comment]
as of 52a12b1, the bug doesn't happen in solo
yet to test in server/MP

**Comment by nr42111** [comment]
On Servers only - this only happens with weapons that "Force Reload" after firing

- M79
- Orca
- M99
- Crossbow
- Buzzsaw Bow

**Comment by KFPilot** [comment]
Fixed by HUD rework. 71645526c20213c7c51ef1e94fcc4326b79134e3
