### ISSUE TITLE
Scrake slow raging bug

### ISSUE THREAD

**Issue by nr42111** [KFPilot/KFTurbo#40]
If the scrake is both Burning and Crispified during sprinting/raged state, it will enter Slow Rage animation
- Repro rate: ~60%

Alt: when a burning Scrake gets Crispified during the sprinting/raged state, it will Slow Rage until the burn wears off.
- Repro rate: 100%
- Steps:
  - Stun Scrake and push it under rage threhold
  - Ignite it immediately
  - Observe it entering slowrage as soon as Crispified is applied, and exiting it as soon as Burning is removed.

**Comment by nr42111** [comment]
update: stunning a scrake during sprint/raging animation causes a slow rage as well.

**Comment by KFPilot** [comment]
Fixed by df4ee16dcaec0fd21e9206e6b8bab79cd0fc9e79.
