### ISSUE TITLE
On Decdicated servers, M79/M32/M4203Nade/(FlareNade) projectiles cannot be disintegrated.

### ISSUE THREAD

**Issue by nr42111** [KFPilot/KFTurbo#44]
- M79 and child projectile classes are immune to siren disintegration.
- Maybe can keep it as a feature (?)
- Sometimes the disintegration visual plays but the projectile keeps living and explodes normally.
- They get destroyed just fine in local/solo play.

**Comment by KFPilot** [comment]
Fixed by b7453ec3ee9f878fa585c1623e20f333c2a033bb.
