### ISSUE TITLE
M79 Grenade Launcher/Schneidzekk(vector) medic gun/HSG shotgun isn't purchaseable

### ISSUE THREAD

**Issue by nr42111** [KFPilot/KFTurbo#5]
Money doesn't get subtracted, weapon doesn't get added to inventory, sound plays though.

Repro: open trader and attempt to buy the weapon.
Affected Weapons:

M79 Grenade Launcher
Schneidzekk medic gun (vector)
HSG Shotgun
Chainsaw

**Comment by KFPilot** [comment]
Fixed by 89e71a0.
