### ISSUE TITLE
UI Improvements - Perk Levels / Icons

### ISSUE THREAD

**Issue by nr42111** [KFPilot/KFTurbo#52]
Some guidelines:
- Avoid very vivid colors (such as pink or piss-yellow)
- Have some sort of system where people can tell at a glance who's the 'higher level' player
- Have lower tiers go up only to 3 stars, and higher tiers go up to 5 stars
- We know that the outlier players are going to be ~lv50 on sharpshooter specifically, so it's a good end-point
- Add some kind of shading to the icon textures, like a border or bevel with a darker color

Example:

Tier 0 - Basic
- Standard KF icons (red)

Tier 1 - Green
- Fill: #19d000
- Border/Bevel: #16b500

Tier 2 - Blue
- Fill: #3f93ff
- Border/Bevel: #3578d9

Tier 3 - Purple
- Fill: #a335ee
- Border/Bevel: #8b2dcd

Tier 4 - Gold
- Fill: #ffd700
- Border/Bevel: #ccac00

Tier 5 - Orange
- Fill: #ff8c19
- Border/Bevel: #cc7015

Tier 6 - Platinum
- Fill: #f3f6f4
- Border/Bevel: #c2c4c3

**Comment by KFPilot** [comment]
- Have some sort of system where people can tell at a glance who's the 'higher level' player
  - No idea what this would mean. Sounds like a bad idea.
- Have lower tiers go up only to 3 stars, and higher tiers go up to 5 stars
  - Weird inconsistency for no particular reason. Sounds like a bad idea.

**Comment by KFPilot** [comment]
Implemented in b06f7952dadf441cf1e0dfcf3ad41057bcb67eab.
