### ISSUE TITLE
Mk23 skins/stickers prevent you from picking up a second Mk23 of a different skin

### ISSUE THREAD

**Issue by nr42111** [KFPilot/KFTurbo#56]
repro:
- buy regular Mk23
- drop it on the ground
- buy KFT/Cyber Mk23
- try to pick up the other one that's dropped

side note:
- there's no dualie skin for the sticker/cyber mk23 variants

**Comment by KFPilot** [comment]
Fixed by 6b4d64aeeaf0de2556433ecdebf7fbe066009011.
