### ISSUE TITLE
Weapons with WeaponHelper / PenetratingWeaponTrace start from penetration 1 instead of 0

### ISSUE THREAD

**Issue by nr42111** [KFPilot/KFTurbo#6]
Hitscan weapons that penetrate lose the penetrationMult on the first target instead of the second and penetrate one less targets.

44 Magnum has a base damage of 108 instead of the expected 120 (0.9)
Bullpup 23 instead of 31 (0.75)

**Comment by KFPilot** [comment]
Fixed by da0b326.
