### ISSUE TITLE
Inconsistent registration of medic darts on players

### ISSUE THREAD

**Issue by DusBus** [KFPilot/KFTurbo#61]
Medic darts frequently fail to register when shot at players. The issue seems to be worse when the target player is at full health, though this is not entirely confirmed. Up to ~8 darts can sometimes fail to register in a row, impacting the Medic  ability to heal and support effectively.

**Comment by KFPilot** [comment]
Seems to be at least mostly fixed in latest. Can reopen if needs improvement.
