### ISSUE TITLE
Change medic gun firemode away from KFHighROFFire.

### ISSUE THREAD

**Issue by KFPilot** [KFPilot/KFTurbo#63]

**Comment by KFPilot** [comment]
KrissM Sounds:
- Mono:
   - KFTurbo.Weapons.KrissM_Fire_M
- Stereo:
   - KFTurbo.Weapons.KrissM_Fire_S
MP5 Sounds:
- Mono:
   - KF_MP5Snd.Fire.MP5_Fire_M
- Stereo:
   - KF_MP5Snd.Fire.MP5_Fire_S
MP7 Sounds:
- Mono:
   - KFTurbo.Weapons.KrissM_Fire_M
- Stereo:
   - KFTurbo.Weapons.KrissM_Fire_S

**Comment by nr42111** [comment]
fixed by d217372
