### ISSUE TITLE
Minor changes & bugfixes

### ISSUE THREAD

**Issue by DusBus** [KFPilot/KFTurbo#65]
- Emote
- Trader arrow missing
- Zed counter missing
- Med darts registering does not play syringe audio Q
- Buy menu - demo perk icon missing in top left
- Ammo counter of reserve ammo behaves incorrectly

**Comment by KFPilot** [comment]
Syringe and Welder are broken atm.

**Comment by KFPilot** [comment]
- ~~Emote~~
- ~~Trader arrow missing~~
- ~~Zed counter missing~~
- Med darts registering does not play syringe audio Q
- Buy menu - demo perk icon missing in top left
- Ammo counter of reserve ammo behaves incorrectly

**Comment by KFPilot** [comment]
- ~~Emote~~
- ~~Trader arrow missing~~
- ~~Zed counter missing~~
- ~~Med darts registering does not play syringe audio Q~~ (going to leave this alone for a bit and see how it feels atm)
- ~~Buy menu - demo perk icon missing in top left~~
- Ammo counter of reserve ammo behaves incorrectly
