### ISSUE TITLE
Super Card - Grenade Whisperer

### ISSUE THREAD

**Issue by nr42111** [KFPilot/KFTurbo#75]
- Increase carrying capacity of grenades by 100%
- Increase damage of grenades by 50-100%
- Increase radius of grenades by 20% (optional)
- Increase healing of medic grenades by 100% (optional)
- Increase AfflictionZap's duration by 50% (optional)

**Comment by KFPilot** [comment]
Added in 6a007df868f6658f839f008f79d4f6ca064567e5.
