### ISSUE TITLE
Crossbow and M99 have unintuitive damage against different large targets

### ISSUE THREAD

**Issue by nr42111** [KFPilot/KFTurbo#77]
| /    | Scrake | Fleshpound | Patriarch |
|------|--------|------------|-----------|
| Xbow | 1440   | 1005       | 2880      | 
| M99  | 2644   | 1387       | 2644      |

Solution 1: Nerf the Xbow and remove the damage multiplier against scrakes and FP
Solution 2: Give the M99 a bonus multiplier against the Patriarch

**Comment by KFPilot** [comment]
Added Patriarch damage bonus for M99 via ce8b833ec39f60d69e65065bf9be21075d768ef6.
