### ISSUE TITLE
Berserker stasis grenades - ground-balance

### ISSUE THREAD

**Issue by nr42111** [KFPilot/KFTurbo#8]
6 Max grenades
increase explosion radius by ~15%

stasis strength:
Scrake - 1 grenade (close to point blank) - 2 grenades(any range in the radius)
FP - 2 grenades (fairly close)  - 3 grenades (any range in the radius)
Patriarch - 3 grenades (fairly close)

remove panic 'dance' from stasis

**Comment by KFPilot** [comment]
First pass done by 6c1e641. Affliction system needs refactor to better support multiple afflictions in a sane way.
